export const sliderData = [
  {
    id: 1,
    img: './assets/slider1.jpg',
  },
  {
    id: 2,
    img: './assets/slider2.jpg',
  },
  {
    id: 3,
    img: './assets/slider3.jpg',
  },
  {
    id: 4,
    img: './assets/slider4.jpg',
  },
];

export const categories = [
  {
    id: 1,
    img: './assets/cat1.jpg',
    title: 'HOME ACCESSORIES',
  },
  {
    id: 2,
    img: './assets/cat2.jpg',
    title: 'FLOWER SERIES',
  },
  {
    id: 3,
    img: './assets/cat3.jpg',
    title: 'SIMPLE DECORATION',
  },
];

export const products = [
  {
    _id: 1,
    name: 'Creative Wall Photo Frame',
    category: 'HOME ACCESSORIES',
    price: 55.99,
    image: './assets/p1.jpg',
    countInStock: 7,
    rating: 4.0,
    numReviews: 5,
    description: `Bring the coastal vibes into your home with our Hantera Decorative Vase. Featuring a unique jug design and made from ceramic in clean ocean tones, available in a range of sizes. Style on its own for a simplistic look or add a touch of greenery or dried grass stems to complete the look.`,
  },
  {
    _id: 2,
    name: 'Dried Flower Bouquet',
    category: 'lSIMPLE DECORATION',
    price: 28.99,
    image: './assets/p2.jpg',
    countInStock: 5,
    rating: 4.0,
    numReviews: 6,
    description: `Bring some boho glam into your life or someone close to your heart.  Our original boho babe bouquet has been updated. Geometric element in the form of small green palm, beauty in the ruscus nestled amongst some native foliage.`,
  },
  {
    _id: 3,
    name: 'Green Dried Flower Bouquet',
    category: 'sSIMPLE DECORATION',
    price: 30.59,
    image: './assets/p3.jpg',
    countInStock: 5,
    rating: 4.0,
    numReviews: 6,
    description: `Bring some boho glam into your life or someone close to your heart.  Our original boho babe bouquet has been updated. Geometric element in the form of small green palm, beauty in the ruscus nestled amongst some native foliage.`,
  },
  {
    _id: 4,
    name: 'Creative Animal Wall Picture',
    category: 'HOME ACCESSORIES',
    price: 80.99,
    image: './assets/p4.jpg',
    countInStock: 5,
    rating: 4.0,
    numReviews: 6,
    description: `Bring some boho glam into your life or someone close to your heart.  Our original boho babe bouquet has been updated. Geometric element in the form of small green palm, beauty in the ruscus nestled amongst some native foliage.`,
  },
  {
    _id: 5,
    name: 'Hantera Decorative Vase',
    category: 'SIMPLE DECORATION',
    price: 22.99,
    image: './assets/p5.jpg',
    countInStock: 5,
    rating: 4.0,
    numReviews: 6,
    description: `Bring some boho glam into your life or someone close to your heart.  Our original boho babe bouquet has been updated. Geometric element in the form of small green palm, beauty in the ruscus nestled amongst some native foliage.`,
  },
  {
    _id: 6,
    name: 'Nature Wall Picture',
    category: 'SIMPLE DECORATION',
    price: 38.99,
    image: './assets/p6.jpg',
    countInStock: 5,
    rating: 4.0,
    numReviews: 6,
    description: `Bring some boho glam into your life or someone close to your heart.  Our original boho babe bouquet has been updated. Geometric element in the form of small green palm, beauty in the ruscus nestled amongst some native foliage.`,
  },
  {
    _id: 7,
    name: 'Artificial Plum Blossom',
    category: 'FLOWER SERIES',
    price: 58.99,
    image: './assets/p7.jpg',
    countInStock: 5,
    rating: 4.0,
    numReviews: 6,
    description: `Bring some boho glam into your life or someone close to your heart.  Our original boho babe bouquet has been updated. Geometric element in the form of small green palm, beauty in the ruscus nestled amongst some native foliage.`,
  },
  {
    _id: 8,
    name: 'LOVE Decor with Elk Model',
    category: 'HOME ACCESSORIES',
    price: 32.99,
    image: './assets/p8.jpg',
    countInStock: 5,
    rating: 4.0,
    numReviews: 6,
    description: `Bring some boho glam into your life or someone close to your heart.  Our original boho babe bouquet has been updated. Geometric element in the form of small green palm, beauty in the ruscus nestled amongst some native foliage.`,
  },
  {
    _id: 9,
    name: 'Modern Pink Ceramic Vase',
    category: 'shakes',
    price: 26.99,
    image: './assets/p9.jpg',
    countInStock: 5,
    rating: 4.0,
    numReviews: 6,
    description: `Bring the coastal vibes into your home with our Hantera Decorative Vase. Featuring a unique jug design and made from ceramic in clean ocean tones, available in a range of sizes. Style on its own for a simplistic look or add a touch of greenery or dried grass stems to complete the look.`,
  },
  {
    _id: 10,
    name: 'Wooden Home Sign Decor',
    category: 'HOME ACCESSORIES',
    price: 36.99,
    image: './assets/p10.jpg',
    countInStock: 5,
    rating: 4.0,
    numReviews: 6,
    description: `Bring the coastal vibes into your home with our Hantera Decorative Vase. Featuring a unique jug design and made from ceramic in clean ocean tones, available in a range of sizes. Style on its own for a simplistic look or add a touch of greenery or dried grass stems to complete the look.`,
  },
  {
    _id: 11,
    name: 'Ballet and Ballerina 3D model',
    category: 'shakes',
    price: 46.99,
    image: './assets/p11.jpg',
    countInStock: 5,
    rating: 4.0,
    numReviews: 6,
    description: `Bring the coastal vibes into your home with our Hantera Decorative Vase. Featuring a unique jug design and made from ceramic in clean ocean tones, available in a range of sizes. Style on its own for a simplistic look or add a touch of greenery or dried grass stems to complete the look.`,
  },
  {
    _id: 12,
    name: 'White Black Dream Catcher Wind Chimes',
    category: 'SIMPLE DECORATION',
    price: 35.99,
    image: './assets/p12.jpg',
    countInStock: 5,
    rating: 4.0,
    numReviews: 6,
    description: `Bring the coastal vibes into your home with our Hantera Decorative Vase. Featuring a unique jug design and made from ceramic in clean ocean tones, available in a range of sizes. Style on its own for a simplistic look or add a touch of greenery or dried grass stems to complete the look.`,
  },
];
